import json
import logging
import os
from datetime import datetime

from sqlalchemy import desc

from radar.db import SessionLocal
from radar.models import Paper

logger = logging.getLogger(__name__)

def build_dashboard() -> None:
    """Generate a static HTML dashboard using data directly from PostgreSQL."""
    try:
        # Load pre-aggregated stats (these were generated by stats.py)
        with open("data/stats/categories.json", "r", encoding="utf-8") as f:
            cat_stats = json.load(f)
    except Exception:
        cat_stats = {}

    db = SessionLocal()
    try:
        # Fetch up to 100 most recent papers for the dashboard
        recent_papers = db.query(Paper).order_by(desc(Paper.created_at)).limit(100).all()
    except Exception as e:
        logger.error(f"Failed to fetch papers from DB for dashboard: {e}")
        recent_papers = []
    finally:
        db.close()

    html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Math Research Radar Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f6f8fa; margin: 0; padding: 20px; color: #24292f; }
        .container { max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }
        h1 { text-align: center; color: #0969da; border-bottom: 1px solid #eaecef; padding-bottom: 10px; }
        .chart-container { width: 100%; max-width: 600px; margin: 30px auto; }
        .paper-list { margin-top: 40px; }
        .paper-item { padding: 15px; border-bottom: 1px solid #eaecef; }
        .paper-item:last-child { border-bottom: none; }
        .paper-title { font-size: 16px; font-weight: 600; color: #0969da; text-decoration: none; }
        .paper-title:hover { text-decoration: underline; }
        .paper-meta { font-size: 12px; color: #57606a; margin-top: 5px; }
        .paper-summary { font-size: 14px; margin-top: 8px; color: #24292f; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; background-color: #ddf4ff; color: #0969da; }
        .source-badge { background-color: #fff8c5; color: #9a6700; margin-left: 5px; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #57606a; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔭 Math Research Radar Dashboard</h1>
        
        <div class="chart-container">
            <canvas id="categoryChart"></canvas>
        </div>

        <div class="paper-list">
            <h2>Latest Discovered Papers (Top 100)</h2>
"""
    
    if not recent_papers:
        html_content += "<p>No papers found in the database.</p>"
    else:
        for p in recent_papers:
            summary = p.summary if p.summary else "No summary available."
            pub_date = p.published[:10] if p.published else "Unknown"
            
            html_content += f"""
            <div class="paper-item">
                <a href="{p.link}" target="_blank" class="paper-title">{p.title}</a>
                <div class="paper-meta">
                    <span class="badge">{p.category}</span>
                    <span class="badge source-badge">{p.source}</span>
                    | Published: {pub_date}
                </div>
                <div class="paper-summary">{summary}</div>
            </div>
"""

    html_content += f"""
        </div>
        <div class="footer">
            Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} | Powered by PostgreSQL
        </div>
    </div>

    <script>
        const ctx = document.getElementById('categoryChart').getContext('2d');
        const data = {json.dumps(cat_stats)};
        new Chart(ctx, {{
            type: 'bar',
            data: {{
                labels: Object.keys(data),
                datasets: [{{
                    label: 'Number of Papers',
                    data: Object.values(data),
                    backgroundColor: '#0969da',
                    borderRadius: 4
                }}]
            }},
            options: {{
                responsive: true,
                plugins: {{
                    title: {{ display: true, text: 'Papers by Mathematical Category' }}
                }}
            }}
        }});
    </script>
</body>
</html>
"""

    # Ensure docs directory exists
    os.makedirs("docs", exist_ok=True)
    with open("docs/index.html", "w", encoding="utf-8") as f:
        f.write(html_content)
    
    logger.info("Successfully generated dashboard at docs/index.html powered by PostgreSQL")