name: GitHub Profile Heartbeat

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Ping File
        run: |
          echo "Last automated check-in: $(date)" > PING.md
          
          # [Definitive] گیت‌هاب فقط کامیت‌های این ایمیل را برای مربع‌های سبز محاسبه می‌کند
          # ایمیل زیر را دقیقاً با ایمیلی که با آن اکانت گیت‌هاب خود را ساخته‌اید جایگزین کنید
          git config --local user.email "YOUR_GITHUB_EMAIL@example.com"
          git config --local user.name "SoheilGtex"
          
          git add PING.md
          git commit -m "chore: daily profile activity ping" || echo "No changes"
          git push